# Site settings
title: Ammar Ratnani's Site
email: ammrat13@gmail.com
github_username: ammrat13
description: >-
    Ammar Ratnani's personal website. It's fairly minimal, containing little
    more than an about section and some blog posts.
repository: "ammrat13/ammrat13.github.io"
baseurl: "/"
url: "https://ammrat13.github.io"

# Build settings
future: false
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: assets/_scss/
kramdown:
    # See: https://stackoverflow.com/questions/25596792/how-do-i-turn-off-smart-quotes-in-jekyll
    smart_quotes: ["apos", "apos", "quot", "quot"]

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
