# Site settings
title: Ammar Ratnani's Site
email: ammrat13@gmail.com
github_username: ammrat13
description: >-
    Ammar Ratnani's personal website. It's fairly minimal, containing little
    more than an about section and some blog posts.
repository: "ammrat13/ammrat13.github.io"
baseurl: "/"
url: "https://ammrat13.github.io"

collections:
    # Collection for the "About Me" section. There's only one thing in it, but
    # doing it this way means we can use Markdown instead of HTML.
    #
    # Just in case we want to add more things in the future, we'll specify a key
    # to order by.
    about:
        sort_by: order

plugins:
    # Create an RSS feed for the posts
  - jekyll-feed

# RSS settings
author:
  name: Ammar Ratnani
  email: ammrat13@gmail.com

# Pagination settings
paginate: 12
paginate_path: "/post_listing/:num"

# Build settings
future: false
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: assets/_scss/
kramdown:
    # See: https://stackoverflow.com/questions/25596792/how-do-i-turn-off-smart-quotes-in-jekyll
    smart_quotes: ["apos", "apos", "quot", "quot"]

# Exclude from processing.
exclude:
    # Exclude packaging files for Ruby and Node
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
    # Exclude dependencies for Ruby and Node
  - vendor/
  - node_modules/
    # Exclude the README and the LICENSE files
  - README.md
  - LICENSE.md
  - LICENSES/
    # Exclude other configuration files
  - linkinator.config.json
