version: 2.1


# This project uses both jekyll and npm
# We'd like both orbs for this to work
orbs:
    ruby: circleci/ruby@1.1.2
    node: circleci/node@4.1.0


# We will only be running on docker
# Define a name for it to prevent duplication
executors:
    docker-exec:
        docker:
            - image: cimg/ruby:2.7-node


# Do the build
jobs:
  build:
    executor: docker-exec
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Which bundler?
          command: bundle -v
