version: 2.1



# This project uses both jekyll and npm
# We'd like both orbs for this to work
orbs:
    ruby: circleci/ruby@1.1.2
    node: circleci/node@4.1.0



# Define names for executors to prevent duplication
executors:

    # Executor for the build-and-test job
    # Has ruby, node, and browsers installed
    build-and-test-exec:
        resource_class: small
        docker:
            - image: cimg/ruby:2.7-browsers

    # Executor for the rebuild-master job
    # We only need a minimal system since we just call Github
    rebuild-master-exec:
        resource_class: small
        docker:
            - image: cimg/base:stable



# Commands for all our logically separate tasks
# Most of them pertain to building and testing
commands:

    # Do the setup steps
    # Checkout the code and install our dependencies
    setup:
        description: Setting up the environment
        steps:
            - checkout
            - ruby/install-deps:
                path: ./vendor/bundle
            - node/install-packages:
                cache-path: ./node_modules
                override-ci-command: npm install

    # Actually build the site
    build:
        description: Building the site
        steps:
            - run: bundle exec jekyll build --future

    # Test that all the links work as expected
    # Ignore some problematic sites
    test-links:
        description: Running Linkinator
        steps:
            - run: |
                npx linkinator \
                    --recurse \
                    --skip https://www.linkedin.com/in/ammar-ratnani \
                    ./_site

    # Do visual regression testing
    test-visual:
        description: Performing visual regression tests
        steps:
            - run: npx percy snapshot ./_site

    # Force a rebuild of the master branch on Github
    # Use the API for this
    rebuild-master:
        description: Rebuilding and publishing the master branch
        steps:
            - run: |
                curl \
                    https://api.github.com/repos/ammrat13/ammrat13.github.io/pages/builds \
                    --request POST \
                    --user "ammrat13:${GITHUB_PERSONAL_ACCESS_TOKEN}" \
                    --header "Accept: application/vnd.github.v3+json"



jobs:

    # Job to do the build and test it
    build-and-test:
        executor: build-and-test-exec
        steps:
            - setup
            - build
            - test-links
            - test-visual

    # Job to force a rebuild of master
    rebuild-master:
        executor: rebuild-master-exec
        steps:
            - rebuild-master



# Workflows to call the jobs
workflows:

    # Defaults for building and testing
    build-and-test:
        jobs:
            - build-and-test

    # Run rebuild-master every day
    rebuild-master:
        jobs:
            - rebuild-master
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only:
                            - master
