version: 2.1


# This project uses both jekyll and npm
# We'd like both orbs for this to work
orbs:
    ruby: circleci/ruby@1.1.2
    node: circleci/node@4.1.0


# We will only be running on docker
# Define a name for it to prevent duplication
executors:
    docker-exec:
        resource_class: small
        docker:
            - image: cimg/ruby:2.7-browsers


# Different commands for the different "phases"
commands:

    # Do the setup steps
    # Checkout the code and install our dependencies
    setup:
        description: Setting up the environment
        steps:
            - checkout
            - ruby/install-deps:
                path: ./vendor/bundle
            - node/install-packages:
                cache-path: ./node_modules
                override-ci-command: npm install

    # Actually build the site
    build:
        description: Building the site
        steps:
            - run: bundle exec jekyll build

    # Test that all the links work as expected
    # Ignore some problematic sites
    test-links:
        description: Running Linkinator
        steps:
            - run: |
                npx linkinator \
                    --recurse \
                    --skip https://www.linkedin.com/in/ammar-ratnani \
                    ./_site

    # Do visual regression testing
    test-visual:
        description: Performing visual regression tests
        steps:
            - run: npx percy snapshot ./_site



# Job to do the build and test it
jobs:
    build-and-test:
        executor: docker-exec
        steps:
            - setup
            - build
            - test-links
            - test-visual


# Workflow to call the job
# Don't do it on master
workflows:
    build-and-test:
        jobs:
            - build-and-test:
                filters:
                    branches:
                        ignore: master
