# Check that the site builds and that links are not broken

name: "Build and Test"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup"
        uses: "./.github/actions/setup"

      - name: "Generate HTML"
        uses: "./.github/actions/build"

      - name: "Run visual regression tests"
        run: |
          npx percy snapshot ./_site
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"

      - name: "Check for broken links"
        uses: "./.github/actions/link-test"
